# apiVersion: v1
# kind: Service
# metadata:
#   name: backend
# spec:
#   clusterIP: 10.100.10.128
#   selector:
#     app: backend
#   ports:
#   - port: 8000
#     targetPort: 8000
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
